---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: selfhosted
spec:
  releaseName: mealie
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
      tag: frontend-v1.0.0beta-3
    env:
      TZ: "${TIMEZONE}"
      DEFAULT_EMAIL: ${SECRET_PERSONAL_EMAIL}
      BASE_URL: https://meals.${SECRET_DOMAIN}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-external"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: &host "meals.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - *host
          secretName: tls.meals
    persistence:
      config:
        enabled: false
        existingClaim: mealie-config
      api-data:
        enabled: true
        existingClaim: mealie-api-data
    api:
      image:
        repository: hkotel/mealie
        tag: api-v1.0.0beta-3
      env:
        TZ: ${TIMEZONE}