---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts-oci
  namespace: flux-system
spec:
  interval: 30m
  type: oci
  url: oci://ghcr.io/bjw-s-labs/helm-charts
