kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate
    namespace: home
stringData:
    mqtt_user: ENC[AES256_GCM,data:HcihAA==,iv:HbOThKiBPF+mF229tW979OC0TKI6hLtABN7yzUErBIM=,tag:KPWC/hVuJfSx/FljgIOeXQ==,type:str]
    mqtt_password: ENC[AES256_GCM,data:P/r2s5F/UDxTn+TqjcpbIbHURhs=,iv:6hPA9etYbUoBWJ41016s512tHR71rWqHylaNYH88+5U=,tag:SsmiushNeJAOZWmKDeU2dw==,type:str]
    doorbell_ip: ENC[AES256_GCM,data:55TwzXs6B/dH0qs2kQ==,iv:EBUduXlTCW0vln0SqowqvEtQZQR/OLid5Y9nY0WgHto=,tag:SI19kL14/O38ycngO/ZH7Q==,type:str]
    doorbell_user: ENC[AES256_GCM,data:bbKWbw4=,iv:l4lfMyfuJuHrwaWQEn8Sk+TkB8GN0DqQgTkk7ZpuUfA=,tag:fczmuhLEwLlJlSXlJi8HWw==,type:str]
    doorbell_password: ENC[AES256_GCM,data:iz2XZZHKkL7LjFJpBCf1lvPqKms=,iv:vGr4NUxjEGgh9JNAnH9VNuSnqDEt40EwB6+Gu7k2IZ4=,tag:2BzAmz5jdzvaA/uI7jUrIw==,type:str]
    front_door_password: ENC[AES256_GCM,data:GFu3CiDA99BHrhI17QqftQ==,iv:7xbC3vB/OedfU8Jbwouw71EPEKcfD7vSymMk9VWxXJg=,tag:FvdyF2QuoWwWm5y8BwPhTQ==,type:str]
    front_door_ip: ENC[AES256_GCM,data:CRuo7vNUUOgw+qhhYg==,iv:FGg3ioFRoLDaJQrhoBQuScaCPC2UlHwY5E1mkBK699A=,tag:QS4+HXKcZY0wArpFjtT//g==,type:str]
    front_door_user: ENC[AES256_GCM,data:8Ypxeg==,iv:QUlZI6q+r7/xbE3F4gK0t7pxT3MGYMKtPWzPOv255X4=,tag:blh5LiwuYJYsNJZH4QyPJw==,type:str]
    garage_password: ENC[AES256_GCM,data:k5eC3eoVKIQjoMUNDLyVAQ==,iv:7rZzXTDm9V9vL8Op2hm1UQZFGr1ofwIv7oGvODh7vGQ=,tag:S9VcrUg/fjFHFpa7S+HW4w==,type:str]
    garage_user: ENC[AES256_GCM,data:nFaD3A==,iv:HcgvEVm1vN07YrEHAPDuc7MBQI3Dsqmj2QdMaIWyD/Q=,tag:5Fdfz2jjSQ6NpwutippLag==,type:str]
    garage_ip: ENC[AES256_GCM,data:aff7KLLihsUg7rds5w==,iv:vzVvHhK1LR9i2OpPrfGFSAc0x2/gZQAgQ40g1DFP74s=,tag:8G47rjXnMtjc7h5+7JDnDA==,type:str]
    cdale_doorbell_user: ENC[AES256_GCM,data:DALb42M=,iv:zVP0IO4UMzjeyKeUyXOzRfciL+c/W2oBFZJt6vSVjQo=,tag:9Hdx3DagHJI1JvUJhKHDtQ==,type:str]
    cdale_doorbell_password: ENC[AES256_GCM,data:Kh3GM+hh,iv:ZXmPZGTZnUc3N1rvykplJofzLdxP7sKqTt4yImHQ8L4=,tag:CIUxZzAPR2fm3bGvYupylQ==,type:str]
    cdale_doorbell_ip: ENC[AES256_GCM,data:NjvE4XgUtlSnFH2S,iv:LMKXR0VH3oZphivVN1uN5bTkA8/HOaenvCrjyOS5V14=,tag:gROhThI9ofEI+/gTaPdzaA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-05-31T22:52:56Z"
          enc: CiQAXmmCQrDOJtkkLik0nm/NDBVZdI+82TfBprzUMqP29mZaC4QSSQA+M8UoZaMluH58mNncO2kGD7QuGme23wrk0VmWITRtcRJUXxfgPzIepttP4eN9xJ+c5rDR+BrO6B4/Mm411pB3MVhZPlFe7JE=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMDJISEgwcCtXUVIzNVpi
            cFJUYmk2UnZVVyttWXVGYm5QanoxcUlwUGl3CmFxeG9ZcTY0SnQrUSsrTzFMY3Vq
            TW5nYWIzdGN1OStONTdydm9DYVVXNHMKLS0tIGNybVN5bzVlT1VDZ09KT0NHYnhM
            UGRvQS9wN2Zsdm5EUXdZZGFILzI3WVUKQK/Me/FQ6ZMXjJBnol9Fh6o8Xo7W6jat
            HTPIEnLUxQdwC5zQLz/aCCiUrwl4bPmjx9+FYfCLZK4aEnRqeO9XIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T19:57:02Z"
    mac: ENC[AES256_GCM,data:gD/n7SAiVcg/JuJxzerjFwyEKcu3tMm4OuznkPdllGTVRDNNPROIe7GJGZ/wS5RG5ElN0giL5pYskIY+KbUb+9/uwW8HRXkyxyRbyKv0HsYOiqQ1/Rx+UDG8rhbKhtfY0UnVeRKqkK0OCHVHv09ZqrLdC9qNl5sQLpe0hryyosY=,iv:qM2juTPfOUZafIWb+rjpsr0ONatrBmg4qcYgh8ZXnJ4=,tag:r1Qne5jdOYvwSApj5OGYdw==,type:str]
    pgp:
        - created_at: "2022-05-31T22:52:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwIXOJznC/BzARAAjC5g07kAOir51JRRT/vek64Ue10awbMMIcaOoSsACAug
            PjL9cU/5+8fb8eVTVGeoaXTn9goxAPeOtT1YynEEyW2qGqD1leTKgXYowdx7SXow
            KEqqAeldIcoTEe5bwlIxSJ/HAQW0t+rS9J2bUqghJHe5nizmMJpUrJLUmgqruxdD
            f4z7QCVYNCSkUl6e6KzoHF1vyEpHTo9wpnARkzo5f3bmUfT2xzgUZf6tcadtWnUr
            nbgaFdgsPwtzsNXCD6XX3XkQTekJKgIHTrPchHkIIIcmGTBvZd0ateLtH7+6vMlP
            bNwDdZ4YUdPAmM7LIbkRdCiXu/vwI9qJexhkewTEznvlkeX3PGgu57winhLVp81R
            k7XlSZOVkUZC8foFnfTWsDp0VDp95M0Qo8loBg6gooYuLmwHkp49ZOIw5lnWPa/G
            iY1P8aFpIpPe3m/DBnxJp+f6GxxdqRiarh38zXKKIUmUYEFirfJi6o27XD1+NQ21
            PdGUE3eodnPLjzD8D4C2l936qb5Jw9XLTt6RtCoE0FSZB+Yv35dgEYGqBqOUBxPJ
            POWRZOjrmH0kHm0Cwww41G2zjizasZyX3OGcA+Nu4WNKVer48w2Z8A2sg6483d8e
            FoSC+0RVyz8EgLVq+JAhI9hQjc5hiEEg/YZTQ/qGVhgIHOCU8+IvwwIcweFufY3S
            XgFr8zFq461R1r+E3KwnytoahnKsLC4Ip63mcKNUp5a37drag4SFXLW+xLWCZT9O
            Kx+3ohANhjzyub52ZTArvlDMjrpDX7GrALE2ubNxilXwC6oA/fPCzkx8TzHgWD8=
            =9f6k
            -----END PGP MESSAGE-----
          fp: 6C9D6C1B579041C3F9A189F9A889A030A843122F
        - created_at: "2022-05-31T22:52:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gPaNBkmDmPARAAhK3u19JqSHErFrgJALvCRIP4S6a8KCc/Y/gxp7aviiWl
            2c5zO3dbFGcQmPIqQeG0eWzvHU0vV85Tnxup156hheEchJzMfOp0aeIGMnr+TWNC
            uABqzufP9/YZNrE00UOY8QS0RxUYrx59iHTFPWNP71IRMIRzdk1nE1dbrJFk3toa
            RywNERYwiWWylFqOKE3TYFDRjAwrPX1gdqnelaFHqe+Pk/WbUs0l+s5AbwOj982N
            9Rim3Q2T9cpTfqKoC/IurxxzuNHfBzTWAvdspD5hP5eKTss+34y80BmvW12RP2Dg
            kajWOsC4pjYCpE+Pl/5p10gCxvdCgobhwMu5ZCLKV3V4pZFhpt0KKSYoOy1wLqD8
            0yaxySjG73yz/K2SAvXADbvxImNWXBey7PfWDTn23kR4NMstsvmMLNnVo9JbAG/g
            2ABM+uOAhGiBErqrcMrEO+vb9CWt1uHLFW9wBqT7UY9/WWlr/m6kx/L6ChXJr1cZ
            xgS5txckWRmmKtkBFPqPr4GQIqfgRuGSP3nOKHvTQf0p0EqLThmKl3MbjoFGKBoD
            93adxIrtVCcCxQdwUTcxVwXzNvGrSrvf0IZdfHfjL+b94mWFWJjtjyho+ISrcCAJ
            T3Yis8M6rV2jawW539tU8NhveQfWdu0V5T+G2aV2Q0k6GWe/C+fJxo/qreJEwLXS
            XgEjSC0QqForNqYZbdHurehgqrCyJH/08oUzqF/Nq371UPwxdK+ZAYEtnQveNsrA
            Pd/70LH8hzzdUE+P9HLZRNYKfax3Eg48TpJA81MpIy9iWMRWC+nyrWNItg3epqo=
            =mz8V
            -----END PGP MESSAGE-----
          fp: 84EEAB5ACBE82B101D59A1025752228D92EE8D9B
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
