---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.3.83

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_LB}
        # externalIPs:
        #   - ${UNIFI_LB}
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.unifi-controller
            hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
      backup:
        enabled: true
        existingClaim: unifi-nfs-backup
        mountPath: /data/backup

    resources:
      requests:
        memory: 500Mi
        cpu: 35m
      limits:
        memory: 750Mi
