---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ocirepository.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: atuin
  app.kubernetes.io/instance: atuin
