---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../global/flux/repositories/git
  - external-snapshotter.yaml
  - k8s-gitops.yaml
  - kube-prometheus-stack.yaml
