---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://itzg.github.io/minecraft-server-charts/
  timeout: 2m
