# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-tandoor
  namespace: selfhosted
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: tandoor-cnpg-secret

  bootstrap:
    initdb:
      # database: postgres
      # owner: postgres
      secret:
        name: tandoor-cnpg-secret

  storage:
    size: 10Gi
    storageClass: ceph-block
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      wal:
        compression: bzip2
      destinationPath: s3://cnpg/
      endpointURL: http://minio.database.svc.cluster.local:9000
      s3Credentials:
        accessKeyId: 
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-creds
  namespace: selfhosted
stringData:
  ACCESS_KEY_ID: ${SECRET_CLUSTER_MINIO_ACCESS_KEY}
  ACCESS_SECRET_KEY: ${SECRET_CLUSTER_MINIO_SECRET_KEY}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tandoor-cnpg-secret
  namespace: selfhosted
stringData:
  superuser-secret: ${TANDOOR_PG_PASSWORD}
  username: postgres
  password: ${TANDOOR_PG_PASSWORD}

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: database
spec:
  schedule: "@daily"
  cluster:
    name: cnpg-tandoor
