---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: tandoor-postgres
  namespace: selfhosted
spec:
  replicas: 1
  image: docker.io/library/postgres:14.5
  database:
    size: 10Gi
    storageClassName: ceph-block
  backup:
    schedule: "0 0 * * *"
    pvcName: tandoor-pg-nfs-backup
    volumeMount: /var/lib/backup
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tandoor-postgres-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tandoor-postgres-secret
          key: replicationUserPassword
