---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    fullNameOverride: nginx-internal

    controller:
      allowSnippetAnnotations: true
      ingressClassResource:
        name: nginx-internal
        default: true
        controllerValue: k8s.io/ingress-nginx-internal

      replicaCount: 3

      service:
        enabled: true
        type: LoadBalancer
        # type: LoadBalancer
        # externalIPs:
        # - "${INTERNAL_NGINX_LB}"
        # loadBalancerIP: "${INTERNAL_NGINX_LB}"
        annotations:
          io.cilium/lb-ipam-ips: ${INTERNAL_NGINX_LB}
        externalTrafficPolicy: Cluster # See https://github.com/JJGadgets/Biohazard/blob/main/kube/deploy/core/_networking/cilium/README.md#preserving-source-ips

      publishService:
        enabled: true

      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values:
                - nginx-internal

      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: 0
        use-forwarded-headers: "true"
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: >-
          403,404,500,501,502,503
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        enable-brotli: "true"
        enable-real-ip: "true"
        log-format-escape-json: "true"
        log-format-upstream: >
          {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
          "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
          "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length,
          "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent"}
        proxy-buffer-size: "16k"

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: network
          namespaceSelector:
            any: true

      extraArgs:
        default-ssl-certificate: "network/${SECRET_DOMAIN/./-}-tls"

      resources:
        requests:
          memory: 400Mi
          cpu: 99m

    defaultBackend:
      enabled: false
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.26.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ghost
        - name: SHOW_DETAILS
          value: "false"
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
