---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  namespace: selfhosted
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: postgres.database.svc.cluster.local
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "false"
  REVERSE_GEOCODING_PRECISION: "2"
  # MACHINE_LEARNING_WORKERS: "1"
  # ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
