---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - ./helmrelease.yaml
  - ./configmap-valheim.yaml
  - ./configmap-valheimplus.yaml
  - ./pvc.yaml
  - ./externalsecret.yaml
  - ./volsync.yaml
