ldap_bind_password: ENC[AES256_GCM,data:iDuwUercu6dhFE5U7i0JT/VfxS+wMcdp7A==,iv:5w8gIEl3QX2KL8xn5wSkj/HxV5AftbVhcEFOmrLfvQ4=,tag:g72KuT8mBoowVe6bKHUPrA==,type:str]
ldap_url: ENC[AES256_GCM,data:Uav88y9DDUHBhqWyFsrr7iFPpqLT2K/+jA==,iv:r8bEPRigXEyvtX+w8/x5d4rO0GttHDmgUDcLu087teU=,tag:nz/o/b93PLL6GPP8bIx7HA==,type:str]
ldap_auth_group_dn: ENC[AES256_GCM,data:AP/vJTSsE9JKnRW6XFa053paFhNOgl4Rh3a/xi2d+nQGsBSlRTvB283Er3xEtFnl,iv:PRKQmVL5eEyKL7t97XX/yoy9UYtiP7ueq2URhEumzLI=,tag:gEYpd+D9/Nru625bF1vOYQ==,type:str]
ldap_auth_user_dn: ENC[AES256_GCM,data:dl6Twej98AnRpisLCwXlmyvnxi++eh2SbFOf/2O+wbCqrCJzLV0=,iv:dvK83jBrYFopOGBUqlNAwrwcJaJh7IM1SzfU1tgBwug=,tag:UMRKv3uu1aY6bmcWY+Q5bg==,type:str]
vault_address: ENC[AES256_GCM,data:fEWV3EvF7m8tz1IKwDghfy7uyj64KSgg8jpc,iv:4gMQykNw+48IsIcpVDiDFMSg1xxD8CDmyoTSpD4Ke0Y=,tag:3XJQz4+oQfuRtZq7iLf42A==,type:str]
vault_token: ENC[AES256_GCM,data:MUsue70rf0+FwwkuaHVaxvTs1G6KobelEPL5ow==,iv:cco00QjlKAqwnrwVkP4iOg7AkCFPj0zJwDvCHeR1ZMU=,tag:BBcmX2xvdaKlxgetrZ8MWg==,type:str]
terraform_app_role: ENC[AES256_GCM,data:A4QNsSROI07uiIkVOzYuJWCM/1OVf+Iq2kyPAZNwEZmSsTSd,iv:nQd7XUWxcgj9fM0ABTiOcMAtaBFsob1Tc6vPcvRsFwc=,tag:odc8tBuNG6v09HsN0epwWw==,type:str]
terraform_secret_id: ENC[AES256_GCM,data:4RZrhIV18wHmGAYUeXBhSDc/QdO71AQGCxsVrVVBWn32VRu1,iv:XDnUxoGxuUXId8ru4iOgxKBITX2k7dZbGJeRaMOEU4o=,tag:FwAVtX4DJe7VateeE0ciIg==,type:str]
ldap_bind_user: ENC[AES256_GCM,data:XmwBTwAWZHAec6a+KruTq/dnJkBrZ8vHmYLC+X/wMvJEscavptFQcOdyub1bktcWhm1Qpa0MIHjNz+q8aHqkD15JdA==,iv:2As29Myy4P22q/qOcRT32e4s42mRk+j5sgwNn5SZHy0=,tag:Cq+XDTLofbeZTdZe4FW2BA==,type:str]
ad_backend_userdn: ENC[AES256_GCM,data:5w2BGQ3RTwW7jPNuk4/TLOzRFZqyc0XIJRS1QAWTMbUK0Z5iss9ZE8Lu1HMxSD7FnLsAocc7vpNz1bc7AgRIUg==,iv:UCs2sudJ/7UAMslwLQwdggK9b56AS57orXzk5bk4xxM=,tag:fMM2ZxZMIPRtykq1Ww94iA==,type:str]
local_domain: ENC[AES256_GCM,data:tqcWtck9tjwGI6633v8=,iv:Zrl2bQTkRmjtVigBEb7765GsvHeG8yYlclsok7Nn3kc=,tag:78OSq5pQBKMNAbbm7Av00w==,type:str]
external_domain: ENC[AES256_GCM,data:D4a5MS8tqA==,iv:ImFEg/1g8uDHZR5Q8PLSFNNRE1mS3xxlyedtFCUXUHQ=,tag:NtbmDl4YTQNVV1/CdFV6Mw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-08-09T21:19:32Z"
          enc: CiQAXmmCQpzQmR8iwlwbnt+UlBw6NT9s41YBpUHOVc82oENTGsgSSQA+M8Uo7hSFAJ9jJ8gIuqEbRIxS28PGKtCpfFHKdGtwoh3becCDnH5DMaaamzPe8QB9BOy3V7Ok4+/DvmnhDQW7MqOeW/f15uQ=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc1BKVGVkbGw0U3kxL3Mz
            Mmp4YUg5ME9zaDBPK1ZOWm5TOEZrM1IvUlY0CjEyYUxTV2JMTHhxajJ0cnhJdVoz
            V3FWYXRlYkkyM1hyd01tQWxrYXVtU2sKLS0tIFZNektndS9qbWhZTUR3TS8zdmpX
            RzZ5MUVicUVpMk9FcnAzWnZvV2ZWaTQKgfPNuat5tHtCw+JqHwvZOjE7m85Z5vzJ
            hieAevgLfmvJlI+5fNSoxyG4U/vWplMbv5dmsO+GbTIcNaYgkbd3nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T21:19:32Z"
    mac: ENC[AES256_GCM,data:62cSpGsHrWA0CvzNXmDDygARm++29wsD4fbm+OkelbkG7f2PXSGU3/sG33F8kw3yISkdSBOUpMH9G/6HH9//VgOmJcYT/RMzuc+Z+anmsi+niwtHrfLuNo1WeB7Upq8cBFkuRMJ7LFMF+3FR6Ek9n8blJIYyObPFpXIShlMpABc=,iv:+4DS6K51uBYi23jSMcD14wsmjbwuy1hGoIkVD7MbJUg=,tag:z+QHnd+/nMA51KsgjthERw==,type:str]
    pgp:
        - created_at: "2022-08-09T21:19:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwIXOJznC/BzAQ/+JuiYd1YxQMfQDO7p2qoyqJaY+DvsIn1gcifA0q/8Dexe
            T71oqZUdN0XyC3+suDIU5lpXvf1JpiMLAmn86n7IqA7KZRp2elp7v6eOV3RTfGB1
            X9Gc/3DT+eCoKXYjknzBSynK0WGMvmtzJ/a72Wa3hWn+13YNeSeuFGWri1VCBiIl
            Q/kl3NwRlveLuJA8YulTKSB6tK1/U4w1be5FP/R+6Zs1+ziYjrILe/ROXoK1/G0+
            3gnsTxtFRupgCOm5CBgLWL9lJfnDoqH8miPqg/Aj9XI3yIQ7IiqbsPjsaaPxenJc
            OM/3qqprmIUYJoJr01ZhcUvm1qZbKgau56OGBqktNSpiLu9CtqWle0ahTCmAwMrh
            VMN4Jd0mQX3YOTvizRJSbz7U5WkJlGDBANyPQjGGuWRH4buHZ+/veTWzzMoplJ0d
            VUsmKpjumPKRn7KpKml83sg8iMGw/2gTyjD7drB+bI6weTgWREtsDjy+UMuuh2ov
            CjSyaswqD5g5xvAsWEIAqmd961iUvf5i45D/aQsyZ87wSp8Ab1SNKveLodCnGOMc
            6D1V8e3lQyhabplWR5KAY2IOELPLn+9jWjR0M4lzvnkNikxBC4VmEXm0eKHYKEnr
            2DTebXhJFyt9NdPfubyg/Wl2CnGNQiseZVapdRnEWKxQjghdoapyckJtHuMOmAbS
            XgEgwyOljCpUV2FCSoo9VRkvlBMSqEcSdxVNJQMURb0+n99jRhH4cZEsolD7Un04
            5DEpuEn3t0Or55wrKgrCVp4uNl6JQDFMWnpA62nj0iPgErN43KkR5Eosy7avQCE=
            =0uo5
            -----END PGP MESSAGE-----
          fp: 6C9D6C1B579041C3F9A189F9A889A030A843122F
        - created_at: "2022-08-09T21:19:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gPaNBkmDmPAQ/8C3V8V9cwI8TtlRKKEmWhJZ0lJgKIx48je7uBLiKcKxTh
            h8W3uATa7jDaZM1Y1H/64L2xYgvtLBkzUgdWqeUXTiEdeNz7Mo87GXtBKmFDlhXe
            waEC2Cfj9YSrD8pClCXYNdPoqsxzE/El4R1brzLat2Es8FYvv3Ash0jqnyGyvs1Z
            I0JbQpLz+CU9CmUwUxkqTWEJnXCdOXLFjQ0W0iV3gmaFU6wnGnE8EQdz0xQ9mv43
            rkwJ4d1jcjtpllubJKmb8o1CnqLMYluld7JGNA04v0AqoSKgSJqSFu2QrzzJF3UA
            UqSuXlYf4Ow/VwpW9oqmaTxnXaxhDNFUpSvflY+PSg1Do1k+s6eAcJ8EmjlY+eTZ
            cpSM/HCYV3AdW66mKeZSG3UiJR4HcxVRP4dj9d5YWi3aer9JAEmiRsnD2KOTOKp/
            DP56+fLl8uDWizdD5vbNr2QpBCYHTNcxxADd0H47OTnTZ8daFIz/U5At/Lei16+1
            GyQFWKS7/o9V94Sda+YSMa+Dl+w8zVBRK5QEEJdrBT0aVD0n8iY2phXHreVE/b4a
            heoA0zzjMwqU4ZypBVikltv7RrpoN9BeuaUD3ZzA82TuXCCgJDV0GUc7sSb5/pDA
            IdWVqc3z0MVWCVV9QFE+NQFSPirNHeXG/Z6xMjoQRt5/Ya8b1vRHssBn67Af5sPS
            XgHmazL3zTcgAvrVy0lQFo7hzPEmS5zXCT2eM7S85oI5925FlCLvYaYc4pZptzV+
            aAfHeanSGqN6Gq6imMsKzEf5SU/a8qMMRWAzmdjlRaUl3VZdfN9ox7mEyH6/SLc=
            =Pg8J
            -----END PGP MESSAGE-----
          fp: 84EEAB5ACBE82B101D59A1025752228D92EE8D9B
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|ldap|app_role|vault|ad|domain|^data$|^stringData))
    version: 3.7.3
