---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-monitoring
resources:
  - ./pvc.yaml
  - ./secret.sops.yaml
  - ./externalsecret.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
