apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: k10-dr-secret
    namespace: kasten-io
stringData:
    key: ENC[AES256_GCM,data:ITcVrFY9OddAsGuQIzc4Ir55YCrL0Nct/+N6ax0jBBmYUXMuCbsNklgi8sF3,iv:z3TCkpk128D10JC8v3FlszMxpCvEA1tCrDtfH7m3Vx0=,tag:BaOsH9RKFdN9+wuOn9IbXw==,type:str]
    clusterId: ENC[AES256_GCM,data:2Rsr6sbmK4oExRjEiQEsOvX9WTHZjpJ8bsXX6xe95cdJPBp+,iv:wL1iy4pC0i0mxy9GT0CPeShCPrRy/SumYfsgp833wM8=,tag:3cbs3hxLFIZw8oSlb8qQEQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-06-13T04:26:07Z"
          enc: CiQAXmmCQhp976aHt3n7Bxb1BlVSamTuAgTuf3kWoULrbzhhumsSSQA+M8UoWP22ddGFpmzR+6H5PsF41KRNzu8JxiG4rrCLg7vR8lLpSntUkmeHvxUKxcvf3VzJsSHmeAa/ZnqJKF07j7wyNncHbXI=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QjZQdEh3TWlLUGpRSFRJ
            SmRpekRNb0ZSU3EzZlFaaE9TMnNEMWtsNEhzCkI4cjZ1WUYrNHdZRFduemo5eTdo
            SmpvQ1NGQzlMaTVRSStzZnA2QnovVGMKLS0tIEY0MEQ4KzVXOWdJbG1vSVZ6ZWRy
            YWVETnNoVHB2clorc3Ria3BjenBGL2cKMtJ7p6qDpU6LBc2pVxjzQLnMeW7ZXArt
            d367S/dgXFg2SHyHf7nL11CEvQWI0UvW7rjTNDjJwRaNMntAdgjCpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T21:37:26Z"
    mac: ENC[AES256_GCM,data:UPzJUB10ifGI8jOkgogiz9rRMpi7XmdV3ATk6EJBx/v4xHtDbMz3FMyxKa0EVPoxwytuJUXCDhcTOa1JXCAQtq4LdZbWhPLqPzIxphDLiC1ihdBHo3QgytMHe1CN9AbgnrOlvTXNIp+pqRNBr9ySAd0s2DjcPtDeuAL5oG6w3vA=,iv:+bH6s8AjM5VeKvb+GOW4oJVOmheygT88Q9Ec1BPr6SA=,tag:sE2NHAK46jP6FmooPd+zfQ==,type:str]
    pgp:
        - created_at: "2022-06-13T04:26:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwIXOJznC/BzAQ/+IbyLLc4v6sGhGBNrUrlR50btQJ8zdHJBZurma/OoGJmB
            hmIhYwwK+EZcTfGeNqDX4TDpMKqHgqBIJHrglDdZ+Vx09i+g997gemHhL8QswUSJ
            H0+dk4cXKt5OjL7EZn4TUYP29LcovNM/TI6csMQYWnS+93X026ELXUyxLZsp1ITP
            FIK2paIvvFPcqspvZ8qC9OdSKg1kS8tiSOV3wRbb1P+BHv4s8GP11P2StLEaSC9M
            0EhsL7b3THozHZabctGJPllDpRH08fiLFFcetT5TDeYRv8xPKWj3Zeyw6Tppv2gw
            MQKgio4sxt3PIE8QkmL8YmTfT4RdG4uRTDwQNecny/pwn5J3ys4abfVKwtl31ZiF
            ZBUGztrLJrKPH80YADRHzgPAuxvfPajZ194HlK6WucewxIr45yVggcJB6/OKzNA6
            UBB5cAnJxX6Aw27xofVuCqLg5VpY1Jhn1WE8JAswI1gl/J6MAQalZv43McafhJDy
            gLP65SxCk2/akzSo1hw13iKMuHhM1VYS++uYP1ofOXjrE8gG8BK5zrb0iy501bxK
            uiksHW0KzZ+xde+0A2ilXV/I1+FoysMlGEn58Iolp0tVFO62Ql5pEdSwcgqhiiMp
            inTGnDyRbnQvgVam+QJnFU4Xrh9P0L/ApIj1+Oqvk0jecy43VA6nNYM4NeeeMHjS
            XgFnWE4ZnT4+UsXtZZ7epy2qrKLzEvtMCUr9iTjux5aq17pytB7+d7yq+SLDx0mO
            1CKdFn2BEi0dYa6EEzAN/VO0UWoux6Fh8UbNiBIfa88S4in5fqf4iavsLffr0TQ=
            =XcAb
            -----END PGP MESSAGE-----
          fp: 6C9D6C1B579041C3F9A189F9A889A030A843122F
        - created_at: "2022-06-13T04:26:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gPaNBkmDmPAQ//T6m0I/tpB1TPsXqqxhmRC1gYf2vvfr32GdsZucI7OmES
            o/mT3R95QE/DguiHBSyRetXZuRSgIk+C9mp1blA/02dYpMhSVCJftIEmWvv+0mM+
            FLvL5xm6+W2s7kBzO71/Zqsq/iaOt2bF8B10o/kRvMLh4QLblIMU1WCpTNlindLl
            wYJ3PUrwZ9/ow4lY0SH/SLwNMB4QMBNR8ndZYBaeqt/QfeYvwUfosoVLvKnN75WR
            MySLPvf8rnvQBR1657VwKNZhmQYi2kxyR01OwRjU2RpU1FKWLFtEntt/citDZAl9
            cTXPbHJMYpnUTAw0OxMRfugpbXhyQoSt+IUd9G4lTIa20Qwpp96UgsEYQtIYnlmj
            hXyPRVgviBu+3gNqixTTAm8FA/rBHb9lIqQWyKHStAB7dYhRWhqTfKR/nw4K2u0W
            vtYgXfHfO79sEj5JAerr1WEm6FHx8yLb+OIpjXhTbiSwj0O1N6GJVRsQeSV4+EMB
            lvVWr4RtQE864M++APopWRK7rE21O0+9Oxvhq7Efc8j7KXP/En/M6IQ0TkQojxnn
            9GQVV4SmLcCm9HVR2Jzm54b9EU2TyJ8GJbEECX0TPpgrSvexM6ysx3shHeR5TNDp
            ERHgEBm+vi4ClUf/c7RYDyd4xaF7lzPt/7dGQXi//dhyr/2tEidhFO6+5LlkPsrS
            XgETIcv50BPWuZ2Kfp67e2qJaEwVsZl3jbtMYJ59KUsSNTWugnzcvJ2yQFnhYNgF
            jMn+7fPIK2TMDIoncKxdHVGbjRdMcf/6uQaA87PM4wTY9kcCfBoyv90NvEq1Ock=
            =gEPi
            -----END PGP MESSAGE-----
          fp: 84EEAB5ACBE82B101D59A1025752228D92EE8D9B
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
