---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  # - ./dev.yaml
  - ./downloads.yaml
  - ./flux-system.yaml
  - ./home.yaml
  - ./kube-system.yaml
  - ./media.yaml
  - ./network.yaml
  - ./rook-ceph.yaml
  # - ./scripts.yaml
  - ./selfhosted.yaml
  - ./system-monitoring.yaml
  - ./system.yaml
  - ./vpn.yaml
  # - ./kasten-io.yaml
  - ./database.yaml
  - ./security.yaml
  - ./gitlab.yaml
  - ./system-controllers.yaml
  # - ./csi-addons-system.yaml
