---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-data
spec:
  storageClassName: paperless-nfs-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/fatguys/k8s/paperless/data
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-export
spec:
  storageClassName: paperless-nfs-export
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/fatguys/k8s/paperless/export
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-incoming
spec:
  storageClassName: paperless-nfs-incoming
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/fatguys/k8s/paperless/incoming
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-media
spec:
  storageClassName: paperless-nfs-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/fatguys/k8s/paperless/media
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-data
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs-data
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-export
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs-export
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-incoming
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs-incoming
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-media
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs-media
  resources:
    requests:
      storage: 1Mi
