# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: enshrouded
#   namespace: selfhosted
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword-connect
#   target:
#     name: enshrouded-secret
#     creationPolicy: Owner
#     template:
#       engineVersion: v2
#       data:

#   dataFrom:
#     - extract:
#         key: gitlab
