---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: system-monitoring
spec:
  dependsOn:
    - name: loki
      namespace: system-monitoring
  interval: 5m
  chart:
    spec:
      chart: vector
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: timberio/vector
      tag: 0.37.1-debian

    role: "Agent"

    podAnnotations:
      configmap.reloader.stakater.com/reload: vector-agent

    podMonitor:
      enabled: true

    service:
      enabled: false

    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

    resources:
      requests:
        cpu: 15m
        memory: 204M
      # limits:
      #   memory: 322M

    customConfig:
      data_dir: /vector-data-dir

      api:
        enabled: false

      # Sources
      sources:
        kubernetes_logs:
          type: kubernetes_logs

        talos_kernel_logs:
          type: socket
          mode: udp
          address: 127.0.0.1:12000

        talos_service_logs:
          type: socket
          mode: udp
          address: 127.0.0.1:12001

      # Sinks
      sinks:
        kubernetes_sink:
          type: vector
          inputs:
            - kubernetes_logs
          address: "vector-aggregator.system-monitoring:6000"
          version: "2"

        talos_kernel_sink:
          type: vector
          inputs:
            - talos_kernel_logs
          address: "vector-aggregator.system-monitoring:6050"
          version: "2"

        talos_service_sink:
          type: vector
          inputs:
            - talos_service_logs
          address: "vector-aggregator.system-monitoring:6051"
          version: "2"
