---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: "node-feature-discovery-worker-conf"
      config:
        core:
          sources:
            - custom
            - pci
            - usb
            - cpu

        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              # - "00"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"

          pci:
            deviceClassWhitelist:
              - "0300"
              - "0880"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          # custom:
          #   # - name: "zigbee"
          #   #   matchOn:
          #   #     - usbId:
          #   #         class: ["ff"]
          #   #         vendor: ["1a86"]
          #   #         device: ["7523"]
          #   # - name: "zwave"
          #   #   matchOn:
          #   #     - usbId:
          #   #         class: ["02"]
          #   #         vendor: ["0658"]
          #   #         device: ["0200"]
          #   - name: "cyberpower-ups"
          #     matchOn:
          #       - usbId:
          #           class: ["03"]
          #           vendor: ["0746"]
          #           device: ["0501"]
          #   # - name: "3dprinter-mpsm"
          #   #   matchOn:
          #   #   - usbId:
          #   #     class: ["02"]
          #   #     vendor: ["2974"]
          #   #     device: ["0503"]
          #   # - name: "3dprinter-ender"
          #   #   matchOn:
          #   #   - usbId:
          #   #     class: ["02"]
          #   #     vendor: ["0483"]
          #   #     device: ["5740"]
          #   # - name: "webcam-c270"
          #   #   matchOn:
          #   #   - usbId:
          #   #     class: ["ef"]
          #   #     vendor: ["046d"]
          #   #     device: ["0825"]
          #   # - name: "canon-dslr"
          #   #   matchOn:
          #   #   - usbId:
          #   #     class: ["00"]
          #   #     vendor: ["04a9"]
          #   #     device: ["317b"]
          #   # - name: "tplink-bluetooth"
          #   #   matchOn:
          #   #   - usbId:
          #   #     class: ["224"]
          #   #     vendor: ["2357"]
          #   #     device: ["0604"]
          #   # - name: "coral-tpu"
          #   #   matchOn:
          #   #     - pciId:
          #   #         vendor: ["1ac1"]
          #   #         device: ["089a"]
          #   # - name: "intel-gpu"
          #   #   matchOn:
          #   #     - pciId:
          #   #         vendor: ["8086"]
          #   #         device: ["0162"]
          #   # - name: "intel-gpu"
          #   #   matchOn:
          #   #     - pciId:
          #   #         vendor: ["8086"]
          #   #         class: ["0600"]
