---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  # - home-assistant-helm-values.enc.yaml
  # - home-assistant-code-server-secret.enc.yaml
  # - home-assistant-postgresql-secret.enc.yaml
  # - home-assistant-secrets.enc.yaml
  # - ha-postgress-secret.sops.yaml
  - pvc.yaml
  # - ./cnpg.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
