apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/network-attachment-definition-client/refs/tags/v1.7.5/artifacts/networks-crd.yaml
  - ocirepository.yaml
  - ./helmrelease.yaml
  # - ./crd.yaml
  - ./rbac.yaml
